import React from 'react';

const Mitigation = () => {
  return (
    <div className="mitigation-page">
      <h1>Vehicle Noise Mitigation Methods</h1>
      <ul>
        <li>
          <h2>Acoustic Barriers or Sound Walls</h2>
          <p>
            Acoustic barriers, commonly referred to as sound walls or noise barriers, are physical structures made of materials designed to absorb or reflect sound waves.
          </p>
        </li>
        <li>
          <h2>Low-Noise Pavement</h2>
          <p>
            Special pavement materials and designs can help reduce tire and road noise generated by vehicles.
          </p>
        </li>
        <li>
          <h2>Traffic Management and Speed Limits</h2>
          <p>
            Implementing traffic management measures, such as speed limits and traffic calming devices, can help reduce noise generated by vehicles.
          </p>
        </li>
        <li>
          <h2>Greenery and Vegetative Buffers</h2>
          <p>
            Planting trees, shrubs, and other vegetation along roadways and highways can act as a natural noise barrier.
          </p>
        </li>
        <li>
          <h2>Quiet Road Design</h2>
          <p>
            Roadway designs that minimize sharp curves, steep grades, and intersections can reduce noise by allowing vehicles to maintain more consistent speeds.
          </p>
        </li>
        <li>
          <h2>Noise-Reducing Tires</h2>
          <p>
            Encouraging or mandating the use of noise-reducing tires on vehicles can help lower tire-road noise.
          </p>
        </li>
        <li>
          <h2>Electric and Hybrid Vehicles</h2>
          <p>
            Electric and hybrid vehicles produce less noise compared to traditional gasoline or diesel vehicles.
          </p>
        </li>
        <li>
          <h2>Noise Barriers in Urban Planning</h2>
          <p>
            In urban planning, zoning regulations can restrict the construction of noise-sensitive buildings (e.g., residential areas) near high-traffic roads.
          </p>
        </li>
        <li>
          <h2>Traffic Signal Synchronization</h2>
          <p>
            Coordinating traffic signals can help reduce traffic congestion and the need for sudden acceleration and braking, which can generate noise.
          </p>
        </li>
        <li>
          <h2>Public Transportation and Alternative Modes</h2>
          <p>
            Encouraging the use of public transportation, cycling, and walking can reduce the overall number of vehicles on the road.
          </p>
        </li>
        <li>
          <h2>Noise Monitoring and Reporting</h2>
          <p>
            Regular noise monitoring and reporting help identify problem areas and assess the effectiveness of mitigation measures.
          </p>
        </li>
      </ul>
    </div>
  );
};

export default Mitigation;
